
name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile

  security-check:
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - uses: actions/checkout@v4

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        output: 'fs-report.json'

    - name: Run Trivy filesystem scan
      run: trivy fs --security-checks vuln,config,secret --format table -o fs-report.json .

    - name: Run Gitleaks scan
      uses: gitleaks/gitleaks-action@v2
      with:
        report-format: 'json'
        report-path: 'gitleaks-report.json'

  test:
    runs-on: ubuntu-latest
    needs: security-check

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test Cases
      run: mvn test
