name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  compile:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  security-check:
    runs-on: self-hosted
    needs: compile  # Wait for compile job first

    steps:
    - uses: actions/checkout@v4

    - name: Install Trivy (Modern Method)
      run: |
        # Install prerequisites
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        
        # Add Trivy repo (modern method without apt-key)
        sudo mkdir -p /etc/apt/keyrings
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /etc/apt/keyrings/trivy.gpg
        echo "deb [signed-by=/etc/apt/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        
        # Install Trivy
        sudo apt-get update -y
        sudo apt-get install -y trivy

    - name: Run Trivy Scan
      run: trivy fs --security-checks vuln,secret --format json -o trivy-report.json .

    - name: Gitleaks Installation
      run: sudo apt install gitleaks -y

    - name: Gitleaks Code Scan
      run: gitleaks detect -s . -r gitleaks-report.json -f json
