name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  compile:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  security-check:
    runs-on: self-hosted
    needs: compile
    steps:
    - uses: actions/checkout@v4

    - name: Clean up system repositories
      run: |
        # Remove conflicting Kubernetes repository
        sudo rm -f /etc/apt/sources.list.d/kubernetes.list || true
        # Clean any duplicate Trivy entries
        sudo rm -f /etc/apt/sources.list.d/trivy.list || true

    - name: Install Trivy (Modern Method)
      run: |
        # Install prerequisites
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        
        # Modern GPG key handling
        sudo mkdir -p /etc/apt/keyrings
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /etc/apt/keyrings/trivy.gpg
        echo "deb [signed-by=/etc/apt/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        
        # Install Trivy
        sudo apt-get update -y
        sudo apt-get install -y trivy

    - name: Install Gitleaks
      run: sudo apt-get install -y gitleaks

    - name: Run security scans
      run: |
        # Run Trivy scan
        trivy fs --security-checks vuln,secret --format json -o trivy-report.json . || echo "Trivy scan completed"
        # Run Gitleaks scan
        gitleaks detect -s . -r gitleaks-report.json -f json || echo "Gitleaks scan completed"
      continue-on-error: true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          trivy-report.json
          gitleaks-report.json

    - name: Fail if secrets detected
      if: always()
      run: |
        if [ -f gitleaks-report.json ] && [ -s gitleaks-report.json ]; then
          echo "::error::SECURITY ALERT: Secrets detected in code!"
          exit 1
        fi

        steps:
          - uses: actions/checkout@v4
    
          - name: Set up JDK 17
            uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

          - name: Unit Test Cases
           run: mvn test

